services:
  - type: web
    name: tecninorte-server
    runtime: node
    region: oregon
    plan: starter
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIRESTORE_OT_COLLECTION
        value: ordenes_trabajo
      - key: FIRESTORE_CLIENTES_COLLECTION
        value: Clientes
      - key: FIRESTORE_CLIENTES_VEHICULOS_COLLECTION
        value: ClientesVehiculos
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        value: bd-tecninorte.firebasestorage.app

  - type: web
    name: tecninorte-web
    runtime: static
    region: oregon
    branch: main
    rootDir: web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeployTrigger: commit
